version: 2
jobs:
  build:
    working_directory: ~/scanapi
    docker:
      - image: circleci/python: 3.7.3
    steps:
      - checkout
      - run:
        command: pip install -r requirements.txt
      - run:
        command: pytest --junit-xml=test-report.xml
      - store_artifacts:
          path: test-report.xml