version: 2
jobs:
  build:
    working_directory: ~/scanapi
    docker:
      - image: circleci/python:3.7.3
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            python setup.py develop
            pip install -e .[dev] .[test]
      - run:
          name: Run tests
          command: ./venv/bin/pytest --cov=./scanapi --cov-report=xml
      - run:
          name: Upload coverage report to codecov.io
          command: ./venv/bin/codecov
  check-black:
    docker:
      - image: circleci/python:3.7.3
    steps:
      - checkout
      - restore_cache:
          key: v3-python-requirements-black
      - run:
          name: Install Black
          command: |
            virtualenv ~/venv-black
            . ~/venv-black/bin/activate
            pip install black==19.10b0
      - save_cache:
          key: v3-python-requirements-black
          paths:
            - "~/venv-black"
      - run:
          name: Run Black check
          command: |
            . ~/venv-black/bin/activate
            black --check .

workflows:
  version: 2
  master:
    jobs:
      - check-black
      - build
